### ISSUE TITLE
Exceptions always being handled twice

### ISSUE THREAD

**Issue by hcd** [Fody/AsyncErrorHandler#11]
Hi,
I love this Fody weaver !
I have one issue and that is that my exceptions always get handled twice right after eachother. It must be something internally because I cannot debug it, and I cannot see where the second call is coming from.

I've made a simple workaround by adapting the AsyncErrorHandler class as following: 

     public static class AsyncErrorHandler
      {
          private static Exception _previousException = null;
       
          public static void HandleException(Exception exception)
        {
            if (ReferenceEquals(_previousException, exception))
                return;//prevent handling twice
            _previousException = exception;
            Debug.WriteLine("AsyncErrorHandler: " + exception.Message + exception.StackTrace);
       }
   }

Then it works fine. Because i'm using ReferenceEquals I'm sure that the exception is actually the exact same instance of the previous exception.

**Comment by SimonCropp** [comment]
@hcd can you upload a repro somewhere?

**Comment by hcd** [comment]
sure no prob, i've uploaded it to www.hcd.be/asyncerrorrepro.zip

it's actually reproducable in less than a minute:
Create a new WPF application
nuget caliburn.micro.start
nuget asyncerrorhandler.fody

Add a button to the view, and a buttonhandler as : 

      public async Task Mybutton()
        {
                Debug.WriteLine("entering buttonhandler");
                string result = await DoSomeStuff();
                MessageBox.Show(result, "Result");
        }

        public async Task<string> DoSomeStuff()
        {
            throw new Exception("oops something went wrong");
            return "Did some stuff !";

        }

And that's it ..the asyncerror handler is being called twice.

**Comment by SimonCropp** [comment]
i think that is actually the correct behaviour. You have two state machines. one for DoSomeStuff and one for Mybutton

The exception handle gets injected into every stemachine. so in this case both DoSomeStuff and  Mybutton. 

But Mybutton calls DoSomeStuff. so since the exception bubbles you get it logged twice. does that make sense?

Not sure how this could be done better. thoughts?

**Comment by hcd** [comment]
hmm ..not sure ...
If I change the button handler to : 
    public async Task Mybutton()
        {
            try
            {
                Debug.WriteLine("entering buttonhandler");
                string result = await DoSomeStuff();
                MessageBox.Show(result, "Result");
            }
            catch (Exception ex)
            {
                MessageBox.Show("Exception caught !");
            }
        }

It triggers the AsyncErrorHandlr just once, but it also shows the messagebox from the catch-handler. Afaik it should only be handled once ? If you have deep calling hierarchies in a real application, it would get handled way too much ?

**Comment by SimonCropp** [comment]
so given there is no state shared between the two handlers how would we implement this?

**Comment by hcd** [comment]
I have honestly no idea, it's quite complex stuff.
But i think my workaround of comparing witht eh "previousexception" is quite effective, it's like signaling the exception has been handled already

**Comment by SimonCropp** [comment]
but that would be a memory leak since a list of all exceptions would need to be kept with no idea of when they can be released

**Comment by hcd** [comment]
It's a static field on a static class, so there's only 1 instance of this variable application wide. Every tme a new exception is thrown, it gets set to the field, and the previous one is released.
Or am I totally missing something here ? :)

**Comment by SimonCropp** [comment]
multiple threads

**Comment by hcd** [comment]
hmmm ..i'll try to fix up a bit more complex case with multithreading and race conditions between the exceptions. But i think that the worst thing that can happen with the workaround is the non-workaround behavior of exceptions being handled multiplitpe times, and that is only when an exception ex1 is handled, in the meantime another exception ex2 on another thread gets thrown and handled (overwriting the "_previousexception" from ex1 to ex2) , and then ex1 gets rehandled (overwriting ex2 with ex1 again, etc..) But that's an extreme case, and then it's just the "normal" behavior anyway. But perhaps i should put a lock() on the _previousexception access :)

**Comment by SimonCropp** [comment]
if you just want to handle this in your handler you can capture the exception in a thread static field and then do a compare

**Comment by SimonCropp** [comment]
closing this. i dont think it can be handled at the weaver level but it can be handles in the implementation of a AsyncErrorHandler

if u can think for a way to solve this at the weaver level then post back here or submit a PR.
