### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by Dids** [Fody/AsyncErrorHandler#15]
With the latest version of both Fody and AsyncErrorHandler (Xamarin.Forms with iOS and Android), I never get further than this:

```
Fody/AsyncErrorHandler:   Executing Weaver 
    MSBUILD : error : Fody: Could not find type 'AsyncErrorHandler'. Expected to find a class with the following signature.
    MSBUILD : error : public static class AsyncErrorHandler
    MSBUILD : error : {
    MSBUILD : error :     public static void HandleException(Exception exception)
    MSBUILD : error :     {
    MSBUILD : error :         Debug.WriteLine("Exception occurred: " + exception.Message);
    MSBUILD : error :     }
    MSBUILD : error : }
```

My `FodyWeavers.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
    <PropertyChanged />
    <RealmWeaver />
    <AsyncErrorHandler />
</Weavers>
```

I've tried moving the weavers around, but that doesn't seem to have any effect, so I'm assuming this project isn't up to date and/or compatible with the latest Fody?

**Comment by SimonCropp** [comment]
do did u add a `AsyncErrorHandler` class?

**Comment by Dids** [comment]
@SimonCropp Thank you, somehow missed that part (assumed it was optional). Compiles fine now, my bad. :)
