### ISSUE TITLE
AsyncErrorHandler package gets auto-removed after successful build (using Fody 4.2.1 and VS2019)

### ISSUE THREAD

**Issue by mzhukovs** [Fody/AsyncErrorHandler#49]
Using VS2019 Enterprise, some very strange behavior where this package gets removed after building.

Steps:
**1)** Added Fody (4.2.1) and then AsyncErrorHandler.Fody (1.2.3) to a .NET Standard 2.0 class library.
**2)** Added the standard AsyncErrorHandler.cs class.
**3)** Rebuilding the project at this point succeeds, but right after I see the package AsyncErrorHandler.Fody gets REMOVED from the project
**4)**  Then of course a subsequent rebuild fails:
> MSBUILD : error : Fody: No weavers found for the configuration entries AsyncErrorHandler. Add the desired weavers via their nuget package.

**Comment by SimonCropp** [comment]
did you read the issue template? https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by mzhukovs** [comment]
No :(
